version: "3.9"
services:
  dbpostgres:
    container_name: db_postgres_ecommerce
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    command: python run.py
    restart: always
    volumes:
      - .:/app
    depends_on:
      - dbpostgres
    environment:
      DATABASE_URL: postgresql://postgres:123@localhost:5432/ecommerce
    ports:
      - "5000:5000"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  db-data:
