version: 2.1

jobs:
  build:
    environment:
      DATABASE_URL: $DATABASE_URL
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run: pip install -r requirements.txt

      - run: pytest

      - run:
          name: Run migrations
          command: |
            alembic upgrade head

  deploy:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Install AWS CLI"
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
            sudo apt-get install -y python3-pip
            sudo pip3 install awsebcli --upgrade

      - run:
          name: "Deploy to Elastic Beanstalk"
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region sa-east-1


            eb init -p docker $APPLICATION --region sa-east-1
            eb deploy $AMBIENT

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feat/user
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feat/user
