    Algoritmos de recomendação:
    Árvores de decisão:
    Algoritmos genéticos:
    Redes Bayesianas:
    SVM (Support Vector Machines):
    PCA (Principal Component Analysis):
    Regressão logística:
    Análise de componentes independentes (ICA):
    K-means clustering:
    Rede de Kohonen:
    Gradient Boosting Machines:
    Random Forests:
    Algoritmos de otimização:
    redes neurais:


    Algoritmos de aprendizado por reforço
    Análise de sentimentos
    Aprendizado semi-supervisionado
    Aprendizado por transferência
    Aprendizado ativo
    Aprendizado não supervisionado
    Algoritmos de detecção de anomalias
    Algoritmos de detecção de fraudes
    Algoritmos de previsão de demanda
    Algoritmos de previsão de tendências
    Algoritmos de segmentação de mercado
    Algoritmos de personalização de conteúdo
    Algoritmos de filtragem de spam
    Algoritmos de detecção de spam
    Algoritmos de recomendação social
    Algoritmos de recomendação de música
    Algoritmos de recomendação de filmes
    Algoritmos de recomendação de produtos
    Algoritmos de reconhecimento de voz
    Algoritmos de reconhecimento de imagem
    Algoritmos de reconhecimento de texto manuscrito
    Algoritmos de detecção de objetos
    Algoritmos de detecção de rosto
    Algoritmos de previsão do tempo
    Algoritmos de análise de risco
    Algoritmos de modelagem de crédito
    Algoritmos de análise de investimentos
    Algoritmos de detecção de intrusão
    Algoritmos de prevenção de fraudes financeiras
    Algoritmos de simulação de sistemas complexos
    Algoritmos de análise de redes sociais
    Algoritmos de reconhecimento de padrões
    Algoritmos de detecção de padrões em séries temporais
    Algoritmos de análise de sentimentos em redes sociais
    Algoritmos de análise de imagem médica
    Algoritmos de recomendação de notícias
    Algoritmos de recomendação de livros
    Algoritmos de análise de mercado de ações
    Algoritmos de tradução automática
    Algoritmos de correção automática
    Algoritmos de segmentação de imagem
    Algoritmos de reconhecimento de fala
    Algoritmos de resumo automático
    Algoritmos de detecção de texto em imagens
    Algoritmos de detecção de emoções
    Algoritmos de previsão de tráfego
    Algoritmos de previsão de consumo de energia
    Algoritmos de otimização de logística
    Algoritmos de otimização de rotas
    Algoritmos de planejamento de projetos
    Algoritmos de detecção de spam de comentários
    Algoritmos de classificação de imagens
    Algoritmos de reconhecimento de objetos em vídeos
    Algoritmos de previsão de vendas
    Algoritmos de previsão de churn
    Algoritmos de detecção de fraude em cartões de crédito
    Algoritmos de análise de voz
    Algoritmos de detecção de discurso de ódio
    Algoritmos de recomendação de restaurantes
    Algoritmos de recomendação de vinhos
    Algoritmos de recomendação de viagens
    Algoritmos de análise de dados de redes sociais
    Algoritmos de classificação de risco de crédito
    Algoritmos de previsão de doenças
    Algoritmos de detecção de doenças
    Algoritmos de diagnóstico médico
    Algoritmos de reconhecimento de voz para comandos de voz
    Algoritmos de recomendação de jogos
    Algoritmos de detecção de ações suspeitas em sistemas de segurança
    Algoritmos de reconhecimento de placas de carros
    Algoritmos de recomendação de cursos
    Algoritmos de previsão de desempenho de funcionários
    Algoritmos de previsão de desgaste de equipamentos
    Algoritmos de previsão de falhas em equipamentos
    Algoritmos de previsão de risco de acidentes
    Algoritmos de previsão de risco de incêndios
    Algoritmos de previsão de risco de desastres naturais
    Algoritmos de detecção de fraudes em seguros
    Algoritmos de previsão de resultados esportivos
    Algoritmos de recomendação de atividades físicas
    Algoritmos de previsão de tendências de moda
    Algoritmos de análise de audiência em mídias sociais
    Algoritmos de recomendação de carros
    Algoritmos de detecção de plágio
    Algoritmos de reconhecimento de padrões em dados geoespaciais
    Algoritmos de detecção de sentimentos em áudio
    Algoritmos de previsão de preços de ações
    Algoritmos de recomendação de investimentos